all: interview

interview: main_menu_client.o company_def.o validation.o applicant_def.o admin_def.o
        gcc main_menu_client.o company_def.o validation.o applicant_def.o admin_def.o -o interview

main_menu_client.o: main_menu_client.c
        gcc -c admin_header.h company_header.h applicant_header.h validation_header.h main_menu_client.c

admin_def.o: admin_def.c
        gcc -c admin_header.h company_header.h applicant_header.h admin_def.c

company_def.o: company_def.c
        gcc -c company_header.h validation_header.h company_def.c

applicant_def.o: applicant_def.c
        gcc -c admin_header.h company_header.h applicant_header.h validation_header.h applicant_def.c

validation.o: validation.c
        gcc -c validation_header.h validation.c

clean:
        rm *.o